# AI
quarkus.langchain4j.chat-model.provider=ollama
quarkus.langchain4j.ollama.base-url=http://localhost:11434/
quarkus.langchain4j.ollama.chat-model.model-id=qwen3:4b
quarkus.langchain4j.ollama.embedding-model.model-id=bge-m3
quarkus.langchain4j.ollama.chat-model.timeout=120000
quarkus.langchain4j.ollama.timeoutt=60000
quarkus.http.io-threads=4
quarkus.vertx.event-loops-pool-size=8
# IRIS
quarkus.datasource.db-kind=iris
quarkus.datasource.username=_SYSTEM
quarkus.datasource.password=SYS
quarkus.datasource.jdbc.driver=com.intersystems.jdbc.IRISDriver
quarkus.datasource.jdbc.url=jdbc:IRIS://localhost:1972/FHIRSERVER

# HTTP
quarkus.http.port=8088
quarkus.http.idle-timeout=0
quarkus.http.limits.max-body-size=16M